### ISSUE TITLE
Arity of operators

### ISSUE THREAD

**Issue by ajaymonga** [orangeduck/BuildYourOwnLisp#100]
Last example in ch 7 [- (* 10 10) (+ 1 1 1)] should be malformed as it supplies 3 arguments to binary + operator. Current Grammar does not enforce the arity. Is this intentional?

**Comment by orangeduck** [comment]
Yes this is intentional. If you supply three or more numbers to any of the operators it will apply that operator to all three. This is also the same in many other lisps. Thanks.
