### ISSUE TITLE
Warn about `-ledit` sooner

### ISSUE THREAD

**Issue by ajimu** [orangeduck/BuildYourOwnLisp#103]
When reading chapter 4, I tried to compile and then went to research why compilation might be failing for me. It was only after I got it to compile that I scrolled to the next section and saw that you had explained about `-ledit`.

I suspect this is probably somewhat common among readers, so it might be worth addressing it in a different way. With that being said, I'm really enjoying the book so far. Thanks a lot

**Comment by orangeduck** [comment]
Thanks - this is a bit of a problem because it doesn't make sense to mention `-ledit` before the changes to the code. Saying that, other people have reported this so I'll have a think about if there are any sensible changes I can make.

Glad you are enjoying the book, happy lisping!
