### ISSUE TITLE
Chapter 8 LERR_BAD_OP will not fire

### ISSUE THREAD

**Issue by schmittyjd** [orangeduck/BuildYourOwnLisp#104]
Instead it will default to using the mpc error instead, trying to figure out how I can get the custom error message to be displayed instead. Any ideas?

**Comment by orangeduck** [comment]
You need to add some more potential operators to the mpc grammar. For example you could switch it to: `operator : '+' | '-' | '*' | '/' | '|' | '&' ;                  \`

**Comment by schmittyjd** [comment]
@orangeduck alright, I see what you mean. I was just wondering about actually overriding the mpc error default if a symbol outside of the defined grammar is used for the BAD_OP error to throw instead, but I'm sure more stuff is coming in the following chapters. Thanks for the quick reply!
