### ISSUE TITLE
I kinda want translate the entire website into Chinese, what should I do?

### ISSUE THREAD

**Issue by 1c7** [orangeduck/BuildYourOwnLisp#105]
First, Great tutorial, Thank you very much :+1:

Second, what should I do to translate the entire website into Chinese?
maybe I should fork,  and then translate all .html file. and pull request?

**Comment by orangeduck** [comment]
Hey,

Someone was already working on a translation. I don't know how far they got but you can check it out [here](https://www.gitbook.com/book/ksco/build-your-own-lisp/details) - and it is on github [here](https://github.com/ksco/BuildYourOwnLispCn).

- Dan

**Comment by 1c7** [comment]
@orangeduck Thanks

**Comment by 1c7** [comment]
@orangeduck  
Seem like he already done. he translate all chapter. and the translation is very good.
Maybe you can put his Github link at bottom of you README
In case someday somebody ask same question

**Comment by orangeduck** [comment]
Sounds good. Maybe I can add the links to the home page as some other translations exist also.

**Comment by orangeduck** [comment]
Okay, added links to translations in the contents page (they fitted better there). :+1:

**Comment by 1c7** [comment]
Cheer
:D
