### ISSUE TITLE
Minor Errata with Chapter 12

### ISSUE THREAD

**Issue by yingw787** [orangeduck/BuildYourOwnLisp#117]
I was getting an issue after completing the initial function: `Error: Unbound Symbol '\'`. I looked at the source code and I realized I needed to add `lenv_add_builtin(e, "\\", builtin_lambda)` to `lenv_add_builtins` and that it wasn't being called anywhere else. Everything else works 🐼  💯

**Comment by orangeduck** [comment]
Thanks! I've updated that chapter.
