### ISSUE TITLE
Minor errata with online text, Chapter 14

### ISSUE THREAD

**Issue by yingw787** [orangeduck/BuildYourOwnLisp#118]
When I tried to run the code at the "Reading Strings" section, it gave me the error "Segmentation Fault: 11". I tried running this on an Ubuntu EC2 instance, and it gave me `<stdin>:1:1: error: expected '-', one or more of one of '0123456789', one or more of one of 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_+-*/\=<>!&', '(', '{' or end of input at '"'`

I fixed this by declaring within ` int main()` `mpc_parser_t* String = mpc_new("string")`, making sure that expr has `<string>` as part of its accepted values, making sure `String` was included within the scope of the mpca_lang declaration, and adding it to the `mpc_cleanup()` function.

**Comment by hscspring** [comment]
have you add `<string>` to the `expr` in `mpca_lang`?

**Comment by hscspring** [comment]
have u add `string: /\"(\\\\.|[^\"])*\"/ ;` in the `mpca_lang`?  
the code here is ok.

**Comment by orangeduck** [comment]
Thanks - yes this is covered in the next section (Comments) but maybe I should make it clearer all the additions that need to be made...
