### ISSUE TITLE
Change the grammar to recognize decimal numbers such as 0.01, 5.21, or 10.2.

### ISSUE THREAD

**Issue by datomnurdin** [orangeduck/BuildYourOwnLisp#122]
I already set regular expression for number, the compiler can receive decimal number but the output not in decimal format.

```
/-?[0-9]+(\\.[0-9]*)?/
```

Please advice. Thank you.

**Comment by orangeduck** [comment]
Please see previous issues: https://github.com/orangeduck/BuildYourOwnLisp/issues/110

**Comment by datomnurdin** [comment]
I'm using this guideline (https://github.com/ethan-thames/ploi-lang/blob/master/ploi.c), thanks!
