### ISSUE TITLE
Chap 4: `<editline/history.h>` does not exist on macOS

### ISSUE THREAD

**Issue by estensen** [orangeduck/BuildYourOwnLisp#124]
To be able to compile the code under the header "Using Editline" one has to remove `#include<editline/history.h>` and compile with `cc -std=c99 -Wall prompt.c -ledit -o prompt`

I don't know if that's also the case for Linux.

More on [Stackoverflow](https://stackoverflow.com/questions/22886475/editline-history-h-and-editline-readline-h-not-found-working-on-osx-when-trying)

**Comment by estensen** [comment]
The solution described further down in the paragraph.

**Comment by SpineyPete** [comment]
I had this issue and indeed simply removing the `#include <editline/history.h>` line does the trick. There's no note of this in the text though, plz fix! :)
