### ISSUE TITLE
Loading files

### ISSUE THREAD

**Issue by AmyShackles** [orangeduck/BuildYourOwnLisp#134]
I'm probably missing something ridiculously obvious, but whenever I try to load a file after finishing Chapter 14, I get the error:

```
Error: Could not load Library hello.lspy:1:23: error: expected '-', one or more of one of '0123456789', one or more of one of 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_+-*/\=<>!&', '"', ';', '(', '{', newline or end of input at end of input
```

hello.lspy in this case contained ```(print "Hello World!")```

Any idea what I'm doing wrong?

**Comment by orangeduck** [comment]
Hi AmyShackles,

Actually I think this is my fault! There was a bug in a recent version of mpc. If you update mpc to the newest version I think it should work for you.

Thanks,

Dan
