### ISSUE TITLE
Different Solution

### ISSUE THREAD

**Issue by firezdog** [orangeduck/BuildYourOwnLisp#135]
I was working through this and came up with a rather different solution -- I don't think the algorithm, if that's the right word to describe it, is quite the same?  Any thoughts on this in terms of best practices?  I think yours is definitely much nicer to read...

```
int evaluate(mpc_ast_t* t) {
    if (strstr(t->tag, "numeral") != 0) {
        return atoi(t->contents);
    } else {
        // seems like the loops is needed here when working your way in to terms on the right.  Perhaps the loop could be replaced with an if check.
        for (int i = 0; i < t->children_num; i++) {
            if (strcmp(t->children[i]->contents,"+") == 0) {
                return atoi(t->children[i+1]->contents) + evaluate(t->children[i+2]);
            } else if (strcmp(t->children[i]->contents, "-") == 0) {
                return atoi(t->children[i+1]->contents) - evaluate(t->children[i+2]);
            } else if (strcmp(t->children[i]->contents, "*") == 0) {
                return atoi(t->children[i+1]->contents) * evaluate(t->children[i+2]);
            } else if (strcmp(t->children[i]->contents, "/") == 0) {
                return atoi(t->children[i+1]->contents) / evaluate(t->children[i+2]);
            }
        }
    }
}
```

**Comment by firezdog** [comment]
Note -- just realized that the returns need to evaluate both expressions on the left and right side of the operator -- that change being made, this solution also seems to work, give or take a few edge cases like + 1 1 1 (which I don't consider to be correctly formed because I think '+' is a binary operator)

**Comment by orangeduck** [comment]
Yeah, the interpretation is up to you so I think this is a good a solution as any if it produces the behaviour you think is right :+1
