### ISSUE TITLE
Average expression for extra points

### ISSUE THREAD

**Issue by MozarellaMan** [orangeduck/BuildYourOwnLisp#148]
I think a cool addition to the extra points part would be to implement an `avg` keyword. Such that:

 `avg 2 4 6 12` => 6

I'd like to suggest this mainly because I've been trying to do it and have been running into segmentation faults left and right...
Would be nice if lots of other people were trying it as well so I could get some help getting it working on my repo 😅

**Comment by orangeduck** [comment]
Nice idea :)
