### ISSUE TITLE
[Chap 9] failed to parse single char '-'

### ISSUE THREAD

**Issue by hpb0412** [orangeduck/BuildYourOwnLisp#176]
I am following the book to chapter 9: s-expression.
I finished the chapter and tried to run all the examples provided.

With case `(- 100)`, my app crashed

Further debugging, I found the parser cannot match the single char `-`.

If it was `+`, the result of the AST would be 
```
> 
  regex 
  expr|symbol|char:1:1 '+'
  regex 
```

But in the case of `-` it was
```
> 
  regex 
  regex
```

It is supposed to be
```
> 
  regex 
  expr|symbol|char:1:1 '-'
  regex 
```

I doubt it is because of the conflict between `number` and `symbol` since both of them fit with single `-` char matching

Playing around to find a solution, I found using `MPCA_LANG_WHITESPACE_SENSITIVE` (instead of `MPCA_LANG_DEFAULT` )fixes everything.

So my question is:
> "Is it mis-typo in the example or  has the latest version of `mpc` changed?"

I don't copy the `mpc.c` and `mpc.h` into my src.
I downloaded the `orangeduck/mpc` and built from src for a static library
- rev. : `d4c99b753bb110cb66c671f6f7c1d8813d24863d`
- committed on Aug 22, 2023
- title: [Merge pull request](https://github.com/orangeduck/mpc/commit/d4c99b753bb110cb66c671f6f7c1d8813d24863d) https://github.com/orangeduck/mpc/pull/167 [from steve-chavez/sepby-repeat](https://github.com/orangeduck/mpc/commit/d4c99b753bb110cb66c671f6f7c1d8813d24863d)

which means it is the latest version at the time of this post

**Comment by orangeduck** [comment]
For me inputting `(- 100)` into the `s_expressions` code works both with the packaged version of mpc and for a fresh copy downloaded from the repo so I am closing this issue. I hope that is okay.
