### ISSUE TITLE
editline includes on OS X

### ISSUE THREAD

**Issue by hellerve** [orangeduck/BuildYourOwnLisp#83]
The [header `editline/history` does not exist on OS X](http://stackoverflow.com/questions/22886475/editline-history-h-and-editline-readline-h-not-found-working-on-osx-when-trying). Including `editline/readline` seems to suffice.

A minimal, hacky fix would be to rewrite the `#else` branch of `#ifdef _WIN32` to :

```c
#ifdef _WIN32
//All the win-specific stuff
#else
#include <editline/readline.h>

#ifndef __APPLE__
#include <editline/history.h>
#endif
#endif
```

which fixes it for me(OS X 10.10).

**Comment by orangeduck** [comment]
I think this header may be required on some older versions of OS X - but I'm not certain so I'll try to look into it a bit more.

**Comment by hellerve** [comment]
I'm not sure about this, but I think I recall `editline` being broken at least since 10.8. Before that, I only know that there have been some problems with Rubys/Pythons REPLs, because the `editline` compatibility layer does not seem to be fully compatible with `readline`.

**Comment by hellerve** [comment]
You could do what feels a bit clumsy and will not be the nicest thing for learners:

```
#if !(MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_8)
#include <editline/history.h>
#else

#endif
```
