### ISSUE TITLE
Suggestion for using linenoise as an alternative to editline

### ISSUE THREAD

**Issue by hckrtst** [orangeduck/BuildYourOwnLisp#97]
I had some issues working with editline on Arch Linux. And decided to try [linenoise](https://github.com/antirez/linenoise). This was pretty easy to use and I was wondering if you might be interested in including it as an alternative option in your updated version of this book.
[Here](https://github.com/hckrtst/cs-refresh/blob/master/buildyourownlisp/InteractivePrompts/basic_repl.c) is an example of how I used it.

**Comment by orangeduck** [comment]
Thanks hckrtst - it is good to see that linenoise can work easily with the rest of the project. Definitely I prefer linenoise to editline for the reasons explained in the linenoise readme. But I think in this case the use of editline is a little bit simpler and easier to explain and additionally should be a little more avaliable across multiple platforms.

But anyway good to see that linenoise works and perhaps others who want to use it can use your post as a reference.

Thanks,

- Dan
